 pipeline {
    agent any
    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
    stages {
        
         stage('Docker Login') {
            steps {
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
              sh """
              cd Kubernetes/comingsoon/
              ansible-playbook playbook.yml
              """
            }
        }
        
        
        stage('Deploy') {
            steps {
              // You will need to install CloudBees AWS Credentials Plugin in Jenkins and add AWS Credentials first 
                
                  sh """
                  cd Kubernetes/comingsoon/k8s
                  kubectl  apply -f deployment.yaml
                  kubectl  apply -f services.yaml
                  """
                }
        

 }}}
