---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop web-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm web-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi triple3a/comingsoon-page
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t snourane/comingsoon-page .
    - name: Login to DockerHub
      command: docker login -u snourane  -p Noura171095
 
  

    - name: Push Image to dockerhub
      command: docker push snourane/comingsoon-page

    - name: run container
      command: docker run -d --name web-container -p 5000:80 snourane/comingsoon-page

